version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /apps/dbd-bot
      - /apps/hues-and-cues
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: docker
    directories:
      - /apps/dbd-bot
      - /apps/hues-and-cues
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker-compose
    directory: /infra
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - '*'
